### ISSUE TITLE
Thread safety of `currentState`

### ISSUE THREAD

**Issue by EricAtPlanGrid** [floschu/Reaktor#1]
While writing a reactor that would cause a resource load to occur, I wanted to guard against loading the same resource… so naturally I would consult `currentState` in my `mutate` function… but then I started to think about threading. I had previously assumed that Reactor might provide some threading guarantees as other similar libraries do, but as far as I can tell `DefaultReactor` will emit `Action`s on whatever thread the `ActionRelay` is used from. Because of this, I believe a stale read of `currentState` could be possible. Do you agree? 

Currently I am mitigating this (disclaimer: I haven't attempted to create a pathological scenario to test this out, so it's still conjecture) by using `transformAction()` to `observeOn(Schedulers.single())`. I'd love to hear your thoughts about this!

Also: thanks for writing such a clear & concise state management library for Android! It fits like a glove with our existing patterns, and we see ourselves standardizing on its usage across the app.

**Comment by floschu** [comment]
The `Reactor` is not intend to handle threading for the user, neither for `state` nor for `action`.

I see your point and understand your use case, but that is exactly why the `transform` functions exist. If you need this behaviour in different places, you should consider extending `Reactor` or `DefaultReactor` and implement it there.
